/*
Generated by Mix
Wed Aug 17 16:25:14 2016 GMT+0200
*/

var Sample = {
	"abi": "[{\"constant\":false,\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"name\":\"set\",\"outputs\":[],\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"get\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"type\":\"function\"},{\"inputs\":[{\"name\":\"v\",\"type\":\"uint256\"}],\"type\":\"constructor\"}]",
	"codeHex": "0x60606040526040516020806062833950608060405251600081905550603b8060276000396000f3606060405260e060020a600035046360fe47b1811460245780636d4ce63c14602e575b005b6004356000556022565b6000546060908152602090f3",
	"name": "Sample"
}

